# Generated by Django 5.2.17 on 2026-09-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='短标识')),
                ('name', models.CharField(max_length=200, verbose_name='选举名称')),
                ('rules_version', models.CharField(default='2026.irv-sfu.v1', max_length=60, verbose_name='规则版本')),
                ('rules_snapshot', models.JSONField(default=dict, verbose_name='规则快照')),
                ('status', models.CharField(choices=[('draft', '草稿（可重算）'), ('published', '已发布（输入与轮次锁定）')], default='draft', max_length=16, verbose_name='状态')),
                ('input_digest', models.CharField(blank=True, default='', max_length=64, verbose_name='输入指纹 SHA256')),
                ('input_summary', models.JSONField(blank=True, default=dict, verbose_name='输入摘要')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近计票时间')),
                ('winner_code', models.CharField(blank=True, default='', max_length=32, verbose_name='当选人代号')),
                ('result_chains', models.JSONField(blank=True, default=dict, verbose_name='选票转移链')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '选举',
                'verbose_name_plural': '选举',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_digest', models.CharField(max_length=64, verbose_name='发布时输入指纹')),
                ('input_summary', models.JSONField(default=dict, verbose_name='发布时输入摘要')),
                ('rules_snapshot', models.JSONField(default=dict, verbose_name='发布时规则快照')),
                ('winner_code', models.CharField(max_length=32, verbose_name='发布的当选人代号')),
                ('rounds_count', models.PositiveIntegerField(verbose_name='发布轮次数')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='irv.election')),
            ],
            options={
                'verbose_name': '结果发布',
                'verbose_name_plural': '结果发布',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='代号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='irv.election')),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('election', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='合成选票代号')),
                ('raw_ranking', models.JSONField(default=dict, verbose_name='原始排名')),
                ('status', models.CharField(blank=True, choices=[('valid', '有效'), ('exhausted', '穷尽'), ('blank', '空白'), ('invalid', '无效')], default='', max_length=16, verbose_name='去脏状态')),
                ('normalized_ranking', models.JSONField(blank=True, default=list, verbose_name='规范化后排名')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='判定说明')),
                ('dropped', models.JSONField(blank=True, default=list, verbose_name='被剔除条目')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='irv.election')),
            ],
            options={
                'verbose_name': '匿名合成选票',
                'verbose_name_plural': '匿名合成选票',
                'ordering': ['code'],
                'unique_together': {('election', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(verbose_name='轮次')),
                ('data', models.JSONField(default=dict, verbose_name='轮次完整数据')),
                ('frozen', models.BooleanField(default=False, verbose_name='已随发布锁定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='irv.election')),
            ],
            options={
                'verbose_name': '计票轮次',
                'verbose_name_plural': '计票轮次',
                'ordering': ['round_no'],
                'unique_together': {('election', 'round_no')},
            },
        ),
    ]
